[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "localize"
version = "0.1.0"
dependencies = ["click>=8", "pyyaml>=6", "typing-extensions>=4.6"]
[project.scripts]
localize = "localize.__main__:cli"
