name: nancy

channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - nodefaults

dependencies:
  - python~=3.11.0
  - pip

  - nodejs~=18.0

  - pytorch~=2.2.0
  - torchvision
  - skorch~=0.15.0

  - numpy
  - scipy
  - matplotlib~=3.8.0
  - scikit-learn~=1.4.0
  - pandas~=2.1.0

  - py-xgboost-cpu~=2.0

  - jupyterlab~=4.0
  - ipywidgets
  - jupyterlab_widgets

  - pyts
  - h5py
  - joblib~=1.3.0

  - dask
  - dvc

  - curl

  - pip:
    - ydata_profiling
    - openpyxl
    - lightning~=2.2
    - lightning-bolts
    - torch-metrics
    - torchinfo
    - pre-commit
    - ruff
    - SciencePlots~=2.1

    - autokeras

    - scikeras
    - -e .
