name: nancy

channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - nodefaults

dependencies:
  - python~=3.11.0
  - pip

  - nodejs~=18.0

  - pytorch~=2.2.0
  - pytorch-cuda=12.1
  - torchvision
  - torchaudio
  - skorch~=0.15.0

  #- nomkl

  - numpy
  - scipy
  - matplotlib~=3.8.0
  - scikit-learn~=1.4.0
  #- scikit-learn-intelex
  - pandas~=2.1.0

  - py-xgboost-cpu~=2.0

  - pyarrow~=14.0
  #- fastparquet

  - jupyterlab~=4.0
  - ipywidgets
  - jupyterlab_widgets

  - pyts
  - h5py
  - joblib~=1.3.0

  - dask
  - dvc

  #- cudatoolkit=12.2
  #- cudnn=8.7

  #- tensorflow
  #- autokeras

  #- snakemake

  - pip:
    #- dvc
    - lightning~=2.2
    - lightning-bolts
    - torch-metrics
    - torchinfo
    - pre-commit
    - ruff
    - SciencePlots~=2.1

    - tensorflow[and-cuda]~=2.15.0
    - autokeras

    - scikeras
    - -e .
