[build-system]
requires = ["setuptools>=40.6.0"]
build-backend = "setuptools.build_meta"


[project]
name = 'nancy-localization'
readme = "README.md"
requires-python = ">=3.11"
version = "2.0.0"


[tool.setuptools.packages.find]
include = ["src*"]
