line-length = 119

output-format = "concise"

# Assume Python 3.11
target-version = "py311"

[lint]

# Enable flake8-bugbear (`B`) rules, isort rules (`I`), pystylewarnings (`W`), in addition to the defaults.
extend-select = ["B", "I", "W"]  # TODO: enable complexity (`C`) rules in the future

# Avoid enforcing line-length violations (`E501`)
ignore = ["E501"]

# Allow fix for all enabled rules (when `--fix`) is provided, except (`B`)
unfixable = ["B"]


[lint.isort]
# List of well known third party libraries. User at sorting imports
known-third-party = [
    "sklearn", "pandas", "numpy", "scipy", "matplotlib",
    "torch", "skorch",
    "keras", "tensorflow", "scikeras",
    "click", "joblib",
]

# Use a single line after each import block.
lines-after-imports = 2


[format]
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
docstring-code-format = true

# Set the line length limit used when formatting code snippets in
# docstrings.
docstring-code-line-length = "dynamic"
