vars:
  - path:
      # Path are relative to location of dvc.yaml file
      scripts: ../../src/umu
      common: ../../src
      data: ../../artifacts/umu/data
      models: ../../artifacts/umu/models
      reports: ../../artifacts/umu/reports

  - splits: [Random, KFold, LeaveOneGroupOut]

  # Models are defined in params.yaml


stages:
  prepare:
    desc: Prepare UMU dataset for the MLOps pipeline
    cmd: |
      unzip ${path.data}/raw/umu.zip -d ${path.data}/raw/
      python ${path.scripts}/prepare.py --method average --input ${path.data}/raw/tcp_nokia_20240325.xlsx --output ${path.data}/interim/umu.pkl
      rm ${path.data}/raw/*.xlsx
      rm ${path.data}/raw/__MACOSX/.*.xlsx
    deps:
      - ${path.scripts}/prepare.py
      - ${path.data}/raw/umu.zip
    outs:
      - ${path.data}/interim/umu.pkl

  eda_raw:
    desc: Exploratory data analysis
    cmd: >
      python ${path.common}/eda.py
      --input ${path.data}/interim/umu.pkl
      --output ${path.reports}/interim/umu.tex
    deps:
      - ${path.common}/eda.py
      - ${path.data}/interim/umu.pkl
    outs:
      - ${path.reports}/interim/umu.tex

  featurize:
    desc: Enrich dataset with additional features
    cmd: >
      python ${path.scripts}/featurize.py
      --input ${path.data}/interim/umu.pkl
      --output ${path.data}/prepared/umu.pkl
    deps:
      - ${path.scripts}/featurize.py
      - ${path.data}/interim/umu.pkl
    outs:
      - ${path.data}/prepared/umu.pkl

  eda_features:
    desc: Exploratory data analysis
    cmd: >
      python ${path.common}/eda.py
      --input ${path.data}/prepared/umu.pkl
      --output ${path.reports}/prepared/umu.tex
    deps:
      - ${path.common}/eda.py
      - ${path.data}/interim/umu.pkl
    outs:
      - ${path.reports}/prepared/umu.tex

  split:
    desc: Split dataset and store indices
    matrix:
      split: ${splits}
    cmd: >
      python ${path.scripts}/split.py
      --input ${path.data}/prepared/umu.pkl
      --split ${item.split}
      --output-indices ${path.data}/splits/${item.split}Split.pkl
    params:
      - split
    deps:
      - ${path.scripts}/split.py
      - ${path.data}/prepared/umu.pkl
    outs:
      - ${path.data}/splits/${item.split}Split.pkl


  gridsearch:
    desc: Determine best hyper-parameters for algorithm on several CVs
    matrix:
      split: ${splits}
      model: ${gridsearch}
    cmd: >
      python ${path.common}/benchmark.py
      --use ${item.model}
      --optimizer gridsearch
      --data ${path.data}/prepared/umu.pkl
      --split-indices ${path.data}/splits/${item.split}Split.pkl
      --output-results ${path.models}/${item.model}-${item.split}Split-results.pkl
    params:
      - gridsearch.${item.model}
    deps:
      - ${path.common}/benchmark.py
      - ${path.data}/prepared/umu.pkl
      - ${path.data}/splits/${item.split}Split.pkl
    outs:
      - ${path.models}/${item.model}-${item.split}Split-results.pkl

  automl:
    desc: Determine best hyper-parameters for algorithm on several CVs
    matrix:
      split: ${splits}
      model: ${automl}
    cmd: >
      python ${path.common}/benchmark.py
      --use ${item.model}
      --optimizer automl
      --data ${path.data}/prepared/umu.pkl
      --split-indices ${path.data}/splits/${item.split}Split.pkl
      --output-results ${path.models}/${item.model}-${item.split}Split-results.pkl
    params:
      - automl.${item.model}
    deps:
      - ${path.common}/benchmark.py
      - ${path.data}/prepared/umu.pkl
      - ${path.data}/splits/${item.split}Split.pkl
    outs:
      - ${path.models}/${item.model}-${item.split}Split-results.pkl


  evaluation:
    cmd: >
      python ${path.common}/report.py
      ${path.models}/*-results.pkl
      --output-report ${path.reports}/metrics.json
    deps:
      - ${path.common}/report.py
      - ${path.models}
    metrics:
      - ${path.reports}/metrics.json:
          cache: false
